<?php


namespace app\modules\backend\controllers;



use app\lib\services\ModelService;
use app\lib\services\RequestService;
use app\lib\services\SendService;
use app\models\Menu;
use app\modules\backend\services\ConfService;
use app\modules\backend\services\MenuService;



class MenuController extends BaseController
{
    public $parent = [];
    public $getAllController = [];
    public function init()
    {
        $this->parent = MenuService::getAllTree();
        $this->getAllController = ConfService::getAllController();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        //TODO 防止用户操作菜单
        $parent = MenuService::getAllTree();
        return $this->render('index',['parent'=>$parent]);
    }
    /**
     * 编辑
     * @return string|\yii\console\Response|\yii\web\Response
     * @throws \app\lib\exception\UserErrorException
     */
    public function actionEdit(){
        if(RequestService::isPost()){
            $post = RequestService::post();
            $Model = new ModelService(Menu::class);
            return $Model->modifyReturn($post['id'],$post);
        }
        $get = RequestService::get();
        $data = Menu::getOneById($get['id']);

        return $this->render('handle',[
            'data'=>$data,
            'controller'=>$this->getAllController,
            'parent'=>$this->parent
        ]);
    }
    /**
     * 添加
     * @return string|\yii\console\Response|\yii\web\Response
     */
    public function actionAdd(){
        if(RequestService::isPost()){
            $post = RequestService::post();
            $Model = new ModelService(Menu::class);
            return $Model->addReturn($post);
        }
        return $this->render('handle',[
            'controller'=>$this->getAllController,
            'parent'=>$this->parent
        ]);
    }
    /**
     * 获取控制里的方法
     * @return \yii\console\Response|\yii\web\Response
     * @throws \ReflectionException
     */
    public function actionGetAction(){
        $get = RequestService::post();
        $controller = $get['controller'];
        $selectControl = ConfService::getActionByController($controller);

        $controller = strtolower(str_replace( 'Controller', '', $controller));
        $str = '';
        foreach($selectControl as $k =>$v ){
            $v =  str_replace( 'action', '', $v);

            preg_match_all(" /[A-Z]/",$v,$matchArr);
            foreach($matchArr[0] as $k1 => $v1){
                if($k1 > 0){
                    $v = str_replace($v1, '-'.strtolower($v1), $v);
                }else{
                    $v = str_replace($v1, strtolower($v1), $v);
                }
            }
            $val =$controller.'/'.$v;

            $str .= "<option value='$val'>$val</option>";
        }
        return SendService::send($str);
    }
    /**
     * 删除
     * @throws \Throwable
     * @throws \app\lib\exception\UserErrorException
     * @throws \yii\db\StaleObjectException
     */
    public function actionDel(){
        $post = RequestService::post();
        if(Menu::delById($post['id'])){
            return SendService::success();
        }else{
            return SendService::error();
        }
    }
    /**
     * 切换
     * @throws \app\lib\exception\UserErrorException
     */
    public function actionSw(){
        $post = RequestService::post();

        $Model = new ModelService(Menu::class);
        if($Model->sw($post['id'])){
            SendService::success();
        }else{
            SendService::error();
        }
    }
    /**
     * 权限树
     * @return \yii\console\Response|\yii\web\Response
     */
    public function actionTree(){
        $Get = RequestService::get();

        //获取所有的菜单整合成树
        $tree = MenuService::toTree(0,$Get['id']);

        return SendService::send(['trees'=>$tree]);

    }
}